name: Deploy-D365-Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'Name of the solution'
        required: true

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Pack Power Platform Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: PowerPlatform/Solutions/${{ inputs.solution-name }}/Managed
        solution-file: artifacts/${{ inputs.solution-name }}.zip
        solution-type: Managed

    - name: Upload Solution Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.solution-name }}
        path: ./artifacts/${{ inputs.solution-name }}.zip


  deploy:
    name: Deploy - EMCR-UAT
    runs-on: windows-latest
    needs: build
    environment: 
      name: EMCR-UAT 
      url: ${{ vars.PP_ENV_URL }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Solution Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.solution-name }}
        path: ./artifacts

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    # - name: Authenticate with Power Platform
    #   uses: microsoft/powerplatform-actions/authenticate@v1
    #   with:
    #     environment-url: ${{ vars.PP_ENV_URL }}
    #     client-id: ${{ vars.PP_APP_ID }}
    #     tenant-id: ${{ vars.PP_TENANT_ID }}
    #     client-secret: ${{ secrets.PP_CLIENT_SECRET }}

    - name: Deploy Solution
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ vars.PP_ENV_URL }}
        app-id: ${{ vars.PP_APP_ID }}
        tenant-id: ${{ vars.PP_TENANT_ID }}
        client-secret: ${{ secrets.PP_CLIENT_SECRET }}
        solution-file: ./artifacts/${{ inputs.solution-name }}.zip
        use-deployment-settings-file: true
        deployment-settings-file: PowerPlatform/Solutions/${{ inputs.solution-name }}/uat.deploymentsettings.json
        async: true
        max-async-wait: 60
        skip-lower-version: true