on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'Name of the solution'
        required: true

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install .NET SDK 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install Power Platform CLI (pac)
      run: |
        # Install Power Platform CLI via PowerShell
        dotnet tool install --global Microsoft.PowerPlatform.Cds.Pac.Cli

    - name: Verify Installations
      run: |
        dotnet --version
        pac --version

    - name: Create Artifacts Directory
      run: |
        if (!(Test-Path -Path "./artifacts")) {
          New-Item -ItemType Directory -Path "./artifacts"
        }

    - name: Pack Solution from Files
      shell: pwsh  # Use PowerShell
      run: |
        $SOLUTION_DIR = "./PowerPlatform/Solutions/${{ inputs.solution-name }}Managed"
        $OUTPUT_FILE = "./artifacts/${{ inputs.solution-name }}.zip"

        if (-not (Test-Path -Path $SOLUTION_DIR)) {
          Write-Host "Error: Solution directory not found: $SOLUTION_DIR"
          exit 1
        }

        Write-Host "Packing solution..."
        pac solution pack --path "$SOLUTION_DIR" --zipfile "$OUTPUT_FILE"

    - name: Upload Solution Artifact
      uses: actions/upload-artifact@v4
      with:
        name: solution-zip
        path: ./artifacts/${{ inputs.solution-name }}.zip


  # deploy:
  #   name: Deploy - EMCR-UAT
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: EMCR-UAT
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4

  #   - name: Download Solution Artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: solution-zip
  #       path: ./artifacts

  #   - name: Authenticate with Power Platform
  #     env:
  #       ENV_URL: ${{ vars.PP_ENV_URL }}              
  #       APP_ID: ${{ vars.PP_APP_ID }}              
  #       TENANT_ID: ${{ vars.PP_TENANT_ID }}        
  #     run: |
  #       pac auth create \
  #         --url "$ENV_URL" \
  #         --applicationId "$APP_ID" \
  #         --clientSecret "${{ secrets.PP_CLIENT_SECRET }}" \
  #         --tenant "$TENANT_ID"

  #   - name: Deploy Solution
  #     run: |
  #       pac solution import \
  #         --path "./artifacts/${{ inputs.solution-name }}.zip" \
  #         --async true \
  #         --max-async-wait 60