name: Pack Power Platform Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'Name of the solution'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform CLI
      run: |
        npm install -g pac-cli

    - name: Pack Solution from Unpacked Files
      shell: bash
      run: |
        set -e  # Exit on error

        SOLUTION_DIR=./PowerPlatform/Solutions/${{ inputs.solution-name }}/Managed
        OUTPUT_FILE=./artifacts/${{ inputs.solution-name }}.zip

        if [ ! -d "$SOLUTION_DIR" ]; then
          echo "Error: Solution directory not found: $SOLUTION_DIR"
          exit 1
        fi

        echo "Packing solution..."
        pac solution pack --path "$SOLUTION_DIR" --zipfile "$OUTPUT_FILE" --managed true
