name: Deploy-D365-Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'Name of the solution'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform CLI
      run: |
        npm install -g pac-cli

    - name: Pack Solution Files
      shell: bash
      run: |
        set -e  # Exit on error

        SOLUTION_DIR=./PowerPlatform/Solutions/${{ inputs.solution-name }}/Managed
        OUTPUT_FILE=./artifacts/${{ inputs.solution-name }}.zip

        if [ ! -d "$SOLUTION_DIR" ]; then
          echo "Error: Solution directory not found: $SOLUTION_DIR"
          exit 1
        fi

        echo "Packing solution..."
        pac solution pack --folder "$SOLUTION_DIR" --zipfile "$OUTPUT_FILE"

    - name: Upload Solution Artifact
      uses: actions/upload-artifact@v4
      with:
        name: solution-zip
        path: ./artifacts/${{ inputs.solution-name }}.zip


  deploy:
    name: Deploy - EMCR-UAT
    runs-on: ubuntu-latest
    needs: build
    environment: EMCR-UAT
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Solution Artifact
      uses: actions/download-artifact@v4
      with:
        name: solution-zip
        path: ./artifacts

    - name: Authenticate with Power Platform
      env:
        ENV_URL: ${{ vars.PP_ENV_URL }}              
        APP_ID: ${{ vars.PP_APP_ID }}              
        TENANT_ID: ${{ vars.PP_TENANT_ID }}        
      run: |
        pac auth create \
          --url "$ENV_URL" \
          --applicationId "$APP_ID" \
          --clientSecret "${{ secrets.PP_CLIENT_SECRET }}" \
          --tenant "$TENANT_ID"

    - name: Deploy Solution
      run: |
        pac solution import \
          --path "./artifacts/${{ inputs.solution-name }}.zip" \
          --async true \
          --max-async-wait 60