name: Deploy D365 Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: "Solution Name"
        required: true
        type: string

jobs:
  build:
    name: Build D365 Solution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pack Solution from Unpacked Files
        shell: pwsh
        run: |
          $solutionDir = "./PowerPlatform/Solutions/${{ inputs.solution-name }}/Unmanaged"
          $outputFile = "./artifacts/${{ inputs.solution-name }}.zip"

          if (-Not (Test-Path -Path $solutionDir -PathType Container)) {
            Write-Host "Error: Solution directory not found: $solutionDir"
            exit 1
          }

          Write-Host "Packing solution..."
          pac solution pack --path $solutionDir --zipfile $outputFile --managed false

      - name: Upload Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: d365-solution
          path: ./artifacts/${{ inputs.solution-name }}.zip
