name: Deploy D365 Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: "Solution Name"
        required: true
        type: string

jobs:
  build:
    name: Build D365 Solution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pack Solution from Unpacked Files
        run: |
          set -e  # Exit if any command fails

          SOLUTION_DIR=./PowerPlatform/Solutions/${{ inputs.solution-name }}/Unmanaged
          OUTPUT_FILE=./artifacts/${{ inputs.solution-name }}.zip

          if [ ! -d "$SOLUTION_DIR" ]; then
            echo "Error: Solution directory not found: $SOLUTION_DIR"
            exit 1
          fi

          echo "Packing solution from directory: $SOLUTION_DIR"

          echo "Packing solution..."
          pac solution pack --path "$SOLUTION_DIR" --zipfile "$OUTPUT_FILE" --managed false


      - name: Upload Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: d365-solution
          path: ./artifacts/${{ inputs.solution-name }}.zip
